name='altered.states'
version='0.8.1'
licence='ISC'
author='Jacob Oscarson'
author_email='jacob@plexical.com'
description = 'Monkey patching for Humans'
url = 'https://github.com/Plexical/altered.states'
